// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Field: typeof import('./src/components/SFormBuilder/Field.vue')['default']
    Filters: typeof import('./src/components/STable/components/Filters.vue')['default']
    'IconMdi:facebook': typeof import('~icons/mdi/facebook')['default']
    'IconMdi:instagram': typeof import('~icons/mdi/instagram')['default']
    'IconMdi:twitch': typeof import('~icons/mdi/twitch')['default']
    'IconMdi:twiter': typeof import('~icons/mdi/twiter')['default']
    Index: typeof import('./src/components/SAlert/Index.vue')['default']
    Item: typeof import('./src/components/SSidebar/Item.vue')['default']
    Pagination: typeof import('./src/components/STable/components/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableRow: typeof import('./src/components/STable/components/TableRow.vue')['default']
  }
}
